version: '3'

services:
  server:
    image: ${REGISTRY}/auth-server:${TAG_NAME}
    restart: on-failure
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock